import Link from "next/link";

export default function TermsOfUse() {
  return (
    <main className="min-h-screen bg-slate-50 font-sans">
      {/* Header */}
      <header className="bg-white border-b border-slate-200 px-6 py-4">
        <div className="max-w-3xl mx-auto flex items-center justify-between">
          <div>
            <Link href="/" className="text-xl font-bold text-slate-800 tracking-tight hover:opacity-80 transition-opacity">
              Myo<span className="text-teal-600">Guard</span> Protocol
            </Link>
            <p className="text-xs text-slate-500 mt-0.5">Physician-Formulated · Data-Driven Muscle Protection</p>
          </div>
          <span className="text-xs bg-teal-50 text-teal-700 border border-teal-200 rounded-full px-3 py-1 font-medium">
            MyoGuard Clinical Oversight
          </span>
        </div>
      </header>

      <div className="max-w-3xl mx-auto px-6 py-10">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-slate-800">Terms of Use</h1>
          <p className="text-sm text-slate-500 mt-2">Last updated: April 2026 · Governing law: Wyoming, USA</p>
        </div>

        <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-8 space-y-8 text-sm text-slate-600 leading-relaxed">

          {/* Introduction */}
          <section>
            <p>
              These Terms of Use (&quot;Terms&quot;) govern your access to and use of the MyoGuard Protocol platform, including the sarcopenia risk calculator, protocol reports, and all associated services (collectively, the &quot;Service&quot;), operated by MyoGuard Protocol, a brand of Meridian Wellness Systems LLC (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;). By accessing or using the Service, you agree to be bound by these Terms. If you do not agree, you must not use the Service.
            </p>
          </section>

          {/* 1. Acceptance */}
          <section>
            <h2 className="text-base font-semibold text-slate-800 mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing the Service, you confirm that you have read, understood, and agree to these Terms. These Terms form a legally binding agreement between you and MyoGuard Protocol. Your continued use of the Service following any modifications to these Terms constitutes acceptance of the revised Terms. We recommend reviewing this page periodically.
            </p>
          </section>

          {/* 2. Nature of the Service */}
          <section>
            <h2 className="text-base font-semibold text-slate-800 mb-3">2. Nature of the Service</h2>
            <p className="mb-3">
              MyoGuard Protocol is an <span className="font-medium text-slate-700">educational and informational tool</span> designed to generate nutritional reference data for individuals on GLP-1 receptor agonist therapy. It is not a medical device, a diagnostic tool, or a clinical decision support system as defined by any regulatory authority.
            </p>
            <ul className="list-disc list-inside space-y-1.5 pl-2 mb-3">
              <li>The Service does <span className="font-medium text-slate-700">not</span> constitute medical advice.</li>
              <li>The Service does <span className="font-medium text-slate-700">not</span> establish a physician–patient relationship between you and MyoGuard Protocol or any affiliated clinician.</li>
              <li>Scores, protocol outputs, and supplement recommendations generated by the Service are reference materials only, not individualised clinical prescriptions.</li>
              <li>The Service is not a substitute for consultation with a licensed healthcare professional.</li>
            </ul>
            <p>
              Always consult your prescribing physician or a qualified healthcare provider before making any changes to your diet, supplementation, or medication regimen.
            </p>
          </section>

          {/* 3. User Eligibility */}
          <section>
            <h2 className="text-base font-semibold text-slate-800 mb-3">3. User Eligibility</h2>
            <p className="mb-3">To use the Service, you must:</p>
            <ul className="list-disc list-inside space-y-1.5 pl-2 mb-3">
              <li>Be at least <span className="font-medium text-slate-700">18 years of age</span>.</li>
              <li>Have the legal capacity to enter into a binding agreement in your jurisdiction.</li>
              <li>Not be using the Service on behalf of a minor.</li>
            </ul>
            <p>
              The Service is intended for adults who are actively under the care of a licensed physician and are currently prescribed a GLP-1 receptor agonist medication. The outputs of this Service are <span className="font-medium text-slate-700">not a substitute for clinical consultation</span>. If you are experiencing a medical emergency, contact your local emergency services immediately.
            </p>
          </section>

          {/* 4. Intellectual Property */}
          <section>
            <h2 className="text-base font-semibold text-slate-800 mb-3">4. Intellectual Property</h2>
            <p className="mb-3">
              All content, software, design, text, scoring algorithms, and branding associated with MyoGuard Protocol — including the MyoGuard name, the MyoGuard Score methodology, the GLP-1 sarcopenia risk calculation model, protocol outputs, and all visual assets — are the exclusive intellectual property of Meridian Wellness Systems LLC and are protected by applicable copyright, trademark, and trade secret laws.
            </p>
            <p className="mb-3">You may not:</p>
            <ul className="list-disc list-inside space-y-1.5 pl-2 mb-3">
              <li>Copy, reproduce, distribute, or republish any part of the Service or its outputs without prior written permission.</li>
              <li>Reverse engineer, decompile, or attempt to extract the scoring algorithm or protocol logic.</li>
              <li>Use the MyoGuard name, logo, or branding in any commercial context without authorisation.</li>
              <li>Create derivative works based on the Service or its content.</li>
            </ul>
            <p>
              Personal, non-commercial use of protocol outputs (e.g. sharing your own report with your physician) is permitted.
            </p>
          </section>

          {/* 5. Prohibited Uses */}
          <section>
            <h2 className="text-base font-semibold text-slate-800 mb-3">5. Prohibited Uses</h2>
            <p className="mb-3">You agree not to use the Service to:</p>
            <ul className="list-disc list-inside space-y-1.5 pl-2">
              <li>Provide medical advice, diagnosis, or treatment recommendations to any third party.</li>
              <li>Misrepresent the outputs of the Service as clinical prescriptions or physician recommendations.</li>
              <li>Scrape, harvest, or systematically extract data from the Service.</li>
              <li>Attempt to gain unauthorised access to any part of the platform, server, or database.</li>
              <li>Upload or transmit malicious code, viruses, or any material that disrupts the Service.</li>
              <li>Use the Service for any unlawful purpose or in violation of any applicable law or regulation.</li>
              <li>Impersonate MyoGuard Protocol, its staff, or any affiliated clinician.</li>
              <li>Use the Service in any way that could harm, disable, overburden, or impair its functionality.</li>
            </ul>
          </section>

          {/* 6. Disclaimer of Warranties */}
          <section>
            <h2 className="text-base font-semibold text-slate-800 mb-3">6. Disclaimer of Warranties</h2>
            <p className="mb-3">
              The Service is provided on an <span className="font-medium text-slate-700">&quot;as is&quot; and &quot;as available&quot;</span> basis without warranty of any kind, express or implied. To the fullest extent permitted by law, MyoGuard Protocol disclaims all warranties including, but not limited to:
            </p>
            <ul className="list-disc list-inside space-y-1.5 pl-2 mb-3">
              <li>Warranties of merchantability, fitness for a particular purpose, and non-infringement.</li>
              <li>Warranties that the Service will be uninterrupted, error-free, or free of viruses or other harmful components.</li>
              <li>Warranties regarding the accuracy, completeness, or clinical appropriateness of any output generated by the Service.</li>
            </ul>
            <p>
              The scoring algorithm and protocol outputs are based on published clinical literature and are subject to revision as evidence evolves. They do not account for individual clinical factors that would be assessed during an in-person consultation.
            </p>
          </section>

          {/* 7. Limitation of Liability */}
          <section>
            <h2 className="text-base font-semibold text-slate-800 mb-3">7. Limitation of Liability</h2>
            <p className="mb-3">
              To the maximum extent permitted by applicable law, MyoGuard Protocol and Meridian Wellness Systems LLC, including their officers, directors, employees, and agents, shall not be liable for any:
            </p>
            <ul className="list-disc list-inside space-y-1.5 pl-2 mb-3">
              <li>Direct, indirect, incidental, special, consequential, or punitive damages.</li>
              <li>Personal injury or health outcomes arising from reliance on Service outputs.</li>
              <li>Loss of data, revenue, or business arising from use of or inability to use the Service.</li>
              <li>Errors or omissions in the content or outputs of the Service.</li>
            </ul>
            <p>
              This limitation applies regardless of whether the claim is based in contract, tort (including negligence), strict liability, or any other legal or equitable theory, even if MyoGuard Protocol has been advised of the possibility of such damages.
            </p>
          </section>

          {/* 8. Governing Law */}
          <section>
            <h2 className="text-base font-semibold text-slate-800 mb-3">8. Governing Law and Jurisdiction</h2>
            <p className="mb-3">
              These Terms are governed by and construed in accordance with the laws of the <span className="font-medium text-slate-700">State of Wyoming, United States</span>, without regard to its conflict of law provisions. Any dispute arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts of Wyoming, USA.
            </p>
            <p>
              Notwithstanding the foregoing, MyoGuard Protocol acknowledges applicable international data protection and consumer protection regulations where required by law, including GDPR (EU/EEA users) and CCPA (California users). Where a conflict exists between these Terms and mandatory local law, local law shall prevail to the extent required.
            </p>
          </section>

          {/* 9. Contact */}
          <section>
            <h2 className="text-base font-semibold text-slate-800 mb-3">9. Contact</h2>
            <p>
              For questions, concerns, or notices regarding these Terms of Use, please contact us at:
            </p>
            <div className="mt-3 bg-slate-50 rounded-lg border border-slate-200 px-4 py-3">
              <p className="font-medium text-slate-700">MyoGuard Protocol, Legal &amp; Compliance</p>
              <p className="mt-1">
                <a href="mailto:legal@myoguard.health" className="text-teal-600 hover:underline">legal@myoguard.health</a>
              </p>
              <p className="mt-1 text-slate-500">Meridian Wellness Systems LLC · 30 N Gould St, STE R, Sheridan, WY 82801</p>
            </div>
          </section>

          {/* 10. Changes */}
          <section>
            <h2 className="text-base font-semibold text-slate-800 mb-3">10. Changes to These Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. When changes are made, the &quot;Last updated&quot; date at the top of this page will be revised. Your continued use of the Service after changes are posted constitutes acceptance of the revised Terms. If you do not agree to the revised Terms, you must discontinue use of the Service.
            </p>
          </section>

        </div>

        {/* Back to homepage */}
        <div className="mt-8 text-center">
          <a
            href="/"
            className="inline-flex items-center gap-2 bg-teal-600 text-white px-6 py-3 rounded-xl text-sm font-medium hover:bg-teal-700 transition-colors"
          >
            ← Back to home
          </a>
        </div>

        <p className="mt-6 text-xs text-slate-400 text-center">
          © 2026 Meridian Wellness Systems LLC · myoguard.health
        </p>
      </div>
    </main>
  );
}
