// MyoGuard — Clinical Evidence Engine: Export Mapper
//
// Core principle:
// MyoGuard generates clinical evidence. The physician generates clinical decisions.
// Never cross that boundary. All outputs are observational. Never diagnostic.
// Never predictive. Never directive.
//
// Maps ClinicalEvidenceRecord to structured export payloads for three surfaces:
//   toPhysicianReport()  — human-readable text for physician documentation support
//   toResearchExport()   — de-identified research payload for registry / publication
//   toEHRPayload()       — HL7 FHIR R4 stub (BUILD 6A — interface contract only)
//
// Pure function — no Prisma access, no UI, no client code.
//
// SECURITY INVARIANT:
//   patientId is NEVER included in research exports.
//   researchParticipantId (UUID from StudyEnrollment) is the ONLY
//   export-safe patient identifier. This constraint must be preserved
//   in all future modifications to toResearchExport().

import type { ClinicalEvidenceRecord } from './types';

// ─── Physician Report ─────────────────────────────────────────────────────────

export interface PhysicianReportPayload {
  /** Short title for the report document. */
  title:    string;
  /** Full plain-text body of the report. */
  body:     string;
  /** Standard CDS disclaimer footer. */
  footnote: string;
}

/**
 * toPhysicianReport()
 *
 * Produces a human-readable plain-text physician report from a ClinicalEvidenceRecord.
 * Suitable for display, printing (via window.print()), and documentation support.
 * All content is observational. No diagnostic or directive language.
 *
 * BUILD 5E: This output will be consumed by the physician-facing evidence UI surface.
 */
export function toPhysicianReport(
  record: ClinicalEvidenceRecord,
): PhysicianReportPayload {
  const {
    patientSummary,
    trajectory,
    continuity,
    adherence,
    physicianSignals,
    documentationNotes,
    evidenceReadiness,
    evidenceGovernance,
    windowDays,
    longitudinalNarrative,
    overallContinuityStatus,
  } = record;

  const lines: string[] = [];

  lines.push('MyoGuard Protocol — Clinical Evidence Record');
  lines.push(`Observation window: ${windowDays} days`);
  lines.push(
    `Generated: ${new Date(evidenceGovernance.generatedAt).toLocaleDateString('en-GB', {
      day: 'numeric', month: 'long', year: 'numeric',
    })}`,
  );
  lines.push('');

  lines.push('PROTOCOL CONTEXT');
  lines.push(`Current band: ${patientSummary.currentBand ?? 'not yet recorded'}`);
  if (patientSummary.glp1Stage)    lines.push(`GLP-1 stage: ${patientSummary.glp1Stage}`);
  if (patientSummary.proteinTargetG) {
    lines.push(`Protein target: ${patientSummary.proteinTargetG}g`);
  }
  lines.push(`Assessments in window: ${patientSummary.assessmentCount}`);
  lines.push(`Check-ins in window: ${patientSummary.checkinCount}`);
  lines.push('');

  lines.push('INTELLIGENCE SIGNALS');
  lines.push(`Band trajectory: ${trajectory.status} (${trajectory.confidence})`);
  lines.push(`Continuity: ${continuity.status} (${continuity.confidence})`);
  lines.push(`Adherence: ${adherence.status} (${adherence.confidence})`);
  const primarySignal = physicianSignals[0];
  if (primarySignal) {
    lines.push(`Physician signal: ${primarySignal.status} (${primarySignal.confidence})`);
  }
  lines.push(`Overall continuity: ${overallContinuityStatus}`);
  lines.push('');

  lines.push('LONGITUDINAL NARRATIVE');
  lines.push(longitudinalNarrative);
  lines.push('');

  if (documentationNotes.length > 0) {
    lines.push('DOCUMENTATION HISTORY');
    documentationNotes.forEach((note, i) => {
      const dateLabel = new Date(note.noteDate).toLocaleDateString('en-GB', {
        day: 'numeric', month: 'short', year: 'numeric',
      });
      lines.push(
        `${i + 1}. ${dateLabel}` +
        (note.overallImpression ? ` — ${note.overallImpression}` : ''),
      );
      if (note.followUpDays) lines.push(`   Follow-up: ${note.followUpDays} days`);
      if (note.note)         lines.push(`   Note: ${note.note}`);
    });
    lines.push('');
  }

  lines.push(
    `Evidence readiness: ${evidenceReadiness.status} ` +
    `(${evidenceReadiness.assessmentCount} assessment${evidenceReadiness.assessmentCount !== 1 ? 's' : ''}, ` +
    `${evidenceReadiness.checkinCount} check-in${evidenceReadiness.checkinCount !== 1 ? 's' : ''})`,
  );

  const footnote =
    'MyoGuard Protocol — Physician-led Clinical Decision Support. ' +
    'All clinical observations generated by the MyoGuard evidence engine are observational only. ' +
    'Clinical interpretation and all clinical decisions remain with the treating physician. ' +
    '© 2026 Meridian Wellness Systems LLC · myoguard.health';

  return {
    title:    `MyoGuard Clinical Evidence Record — ${windowDays}-day window`,
    body:     lines.join('\n'),
    footnote,
  };
}

// ─── Research Export ──────────────────────────────────────────────────────────
//
// SECURITY INVARIANT:
//   patientId is NEVER included in this payload.
//   researchParticipantId (UUID from StudyEnrollment) is the sole patient identifier.
//   If researchParticipantId is unavailable, the field defaults to "not_available"
//   and the consuming layer should treat this export as ineligible.

export interface ResearchExportPayload {
  /** UUID from StudyEnrollment.researchParticipantId — sole patient identifier. */
  researchParticipantId:   string;
  windowDays:              number;
  generatedAt:             string;
  protocolVersion:         string;
  intelligenceVersion:     string;
  evidenceReadiness:       string;
  trajectoryStatus:        string;
  continuityStatus:        string;
  adherenceStatus:         string;
  physicianSignalStatus:   string;
  overallContinuityStatus: string;
  assessmentCount:         number;
  checkinCount:            number;
  documentationCount:      number;
}

export interface ResearchExportOptions {
  /**
   * Must be sourced from StudyEnrollment.researchParticipantId.
   * Never pass patientId or any other user identifier here.
   */
  researchParticipantId?: string;
}

/**
 * toResearchExport()
 *
 * Produces a de-identified research payload from a ClinicalEvidenceRecord.
 * Compatible with R, SPSS, Python, and CSV statistical workflows.
 *
 * patientId is NEVER included. researchParticipantId is the only identifier.
 * If neither the options param nor exportMetadata provides a researchParticipantId,
 * the field is set to "not_available" — consuming layers must check this.
 */
export function toResearchExport(
  record: ClinicalEvidenceRecord,
  options?: ResearchExportOptions,
): ResearchExportPayload {
  // Resolve researchParticipantId — options param takes precedence over record metadata.
  // NEVER fall back to patientId. "not_available" signals ineligible export.
  const researchParticipantId =
    options?.researchParticipantId ??
    record.exportMetadata.researchParticipantId ??
    'not_available';

  return {
    researchParticipantId,
    windowDays:             record.windowDays,
    generatedAt:            record.generatedAt,
    protocolVersion:        record.evidenceGovernance.protocolVersion,
    intelligenceVersion:    record.evidenceGovernance.intelligenceVersion,
    evidenceReadiness:      record.evidenceReadiness.status,
    trajectoryStatus:       record.trajectory.status,
    continuityStatus:       record.continuity.status,
    adherenceStatus:        record.adherence.status,
    physicianSignalStatus:  record.physicianSignals[0]?.status ?? 'within_expected_range',
    overallContinuityStatus: record.overallContinuityStatus as string,
    assessmentCount:        record.patientSummary.assessmentCount,
    checkinCount:           record.patientSummary.checkinCount,
    documentationCount:     record.documentationNotes.length,
  };
}

// ─── EHR Export Stub — BUILD 6A ───────────────────────────────────────────────
//
// HL7 FHIR R4 payload stub. Not yet implemented.
// When implemented in BUILD 6A, this will produce a FHIR R4 Observation bundle
// mapping ClinicalEvidenceRecord signals to structured FHIR Observation resources.
//
// Reference: https://www.hl7.org/fhir/observation.html
// Bundle type: "collection"
// Resource type: Observation (https://www.hl7.org/fhir/observation.html)
// Code system target: LOINC / SNOMED CT (to be determined in BUILD 6A)

export interface EHRPayloadStub {
  resourceType: 'Bundle';
  type:         'collection';
  status:       'not_implemented';
  buildTarget:  'BUILD_6A';
  note:         string;
}

/**
 * toEHRPayload()
 *
 * Stub — returns a typed placeholder preserving the interface contract for BUILD 6A.
 * The _record parameter is intentionally unused; the underscore prefix is deliberate.
 */
export function toEHRPayload(
  _record: ClinicalEvidenceRecord,
): EHRPayloadStub {
  return {
    resourceType: 'Bundle',
    type:         'collection',
    status:       'not_implemented',
    buildTarget:  'BUILD_6A',
    note:         'HL7 FHIR R4 export is planned for BUILD 6A. This stub preserves the interface contract.',
  };
}
