// MyoGuard — Clinical Evidence Engine: Longitudinal Summary
//
// Core principle:
// MyoGuard generates clinical evidence. The physician generates clinical decisions.
// Never cross that boundary. All outputs are observational. Never diagnostic.
// Never predictive. Never directive.
//
// Generates an observational longitudinal narrative from EvidenceSummary signals.
// Called by evidencePacket.ts; result is stored in ClinicalEvidenceRecord.longitudinalNarrative.
//
// Pure function — no Prisma access, no UI, no client code.
//
// Vocabulary governance:
//   PREFER: observed, recorded, continuity concern, review signal, requiring attention,
//           pattern observed, trajectory recorded, documented
//   NEVER:  worsening, deteriorating, urgent, severe, predicted, forecast,
//           recommendation, diagnosis, improving (unqualified), will, may worsen

import type { EvidenceSummary, IntelligenceSignal } from './types';

// ─── Status → observational text maps ────────────────────────────────────────
//
// Status values are taken verbatim from intelligence/types.ts status unions.
// All text is observational — no prognostic or directive language.

const TRAJECTORY_TEXT: Record<string, string> = {
  stable:            'band trajectory has remained stable across the review window',
  positive_trend:    'a positive band trajectory has been observed across the review window',
  variable:          'band trajectory has been variable across the review window',
  declining_trend:   'a declining band trajectory has been recorded across the review window',
  insufficient_data: 'insufficient assessment data is available to characterise band trajectory',
};

const CONTINUITY_TEXT: Record<string, string> = {
  engaged:           'patient continuity is active within the review window',
  inconsistent:      'continuity has been inconsistent within the review window',
  inactive:          'a continuity concern has been observed — limited check-in activity recorded',
  insufficient_data: 'insufficient check-in data is available to assess continuity',
};

const ADHERENCE_TEXT: Record<string, string> = {
  target_achieved:   'protein adherence has been recorded at or above protocol target',
  near_target:       'protein adherence has been recorded near protocol target',
  persistent_deficit:'a protein adherence deficit has been recorded across recent check-ins',
  insufficient_data: 'insufficient adherence data is available within the review window',
};

const PHYSICIAN_SIGNAL_TEXT: Record<string, string> = {
  review_recommended:       'a physician review signal has been recorded',
  review_threshold_crossed: 'a physician review threshold has been crossed — recorded for physician attention',
  continuity_concern:       'a continuity concern signal has been recorded for physician awareness',
  within_expected_range:    'no physician review signal observed — observations within expected range',
};

// Resolves a status string against a text map.
// Falls back to a normalised representation of the raw status when not found.
function resolveText(map: Record<string, string>, status: string): string {
  return map[status] ?? `status recorded as "${status}"`;
}

// ─── Primary export ───────────────────────────────────────────────────────────

/**
 * generateLongitudinalNarrative()
 *
 * Produces a plain-text observational narrative from the four evidence
 * signal dimensions. Used as ClinicalEvidenceRecord.longitudinalNarrative.
 *
 * Output is a single paragraph suitable for physician report display
 * and as a documentation support artefact.
 * All statements are observational. None are diagnostic or predictive.
 */
export function generateLongitudinalNarrative(
  trajectory:      EvidenceSummary,
  continuity:      EvidenceSummary,
  adherence:       EvidenceSummary,
  physicianSignals: IntelligenceSignal[],
  windowDays:      number,
): string {
  const lines: string[] = [];

  lines.push(
    `MyoGuard Clinical Evidence Record — ${windowDays}-day observational window.`,
  );

  const trajectoryBase = resolveText(TRAJECTORY_TEXT, trajectory.status);
  const assessmentNote = trajectory.dataPoints > 0
    ? ` Based on ${trajectory.dataPoints} assessment${trajectory.dataPoints !== 1 ? 's' : ''}.`
    : '';
  lines.push(`Band trajectory: ${trajectoryBase}.${assessmentNote}`);

  lines.push(`Continuity: ${resolveText(CONTINUITY_TEXT, continuity.status)}.`);

  lines.push(`Adherence: ${resolveText(ADHERENCE_TEXT, adherence.status)}.`);

  const primarySignal = physicianSignals[0];
  if (primarySignal) {
    lines.push(
      `Physician signals: ${resolveText(PHYSICIAN_SIGNAL_TEXT, primarySignal.status)}.`,
    );
  }

  lines.push(
    'All observations are generated by the MyoGuard evidence engine. ' +
    'Clinical interpretation and all clinical decisions remain with the treating physician.',
  );

  return lines.join(' ');
}
